version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build: ./Back
    container_name: backend
    env_file:
      - ./Back/.env
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - app-networks
    restart: unless-stopped

  frontend:
    build: ./Front
    container_name: frontend
    env_file:
      - ./Front/.env
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - app-networks

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-networks

volumes:
  db_data:

networks:
  app-networks:
    driver: bridge
