
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-networks

  backend:
    build: ./Back
    container_name: backend
    env_file:
      - ./Back/.env
    depends_on: 
      - mysql
    networks:
      - app-networks

  frontend:
    build: ./Front
    container_name: frontend
    env_file:
      - ./Front/.env
    depends_on:
      - backend
    networks:
      - app-networks

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-networks

volumes:
  db_data:
    driver: local

networks:
  app-networks:
    driver: bridge
