
version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-networks

  backend:
    build: ./Back
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-networks

  frontend:
    build: ./Front
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-networks

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-networks

volumes:
  db_data:

networks:
  app-networks:
