version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-networks

  backend:
    build: ./Back
    container_name: backend
    restart: always
    env_file:
      - ./Back/.env
    depends_on:
      - mysql
    networks:
      - app-networks
    expose:
      - "3000" # exposto apenas para a rede interna (Nginx)

  frontend:
    build:
      context: ./Front
      args:
        VITE_API_URL: https://todo.local/api/
    container_name: frontend
    restart: always
    env_file:
      - ./Front/.env
    depends_on:
      - backend
    networks:
      - app-networks
    expose:
      - "3000"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-networks

volumes:
  db_data:
    driver: local

networks:
  app-networks:
    driver: bridge
